// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEhvOKoOEtbloWWI2mRIZgTHnfM_TbsA',
    appId: '1:368896919076:web:5bdb0f75f6650d62043ab1',
    messagingSenderId: '368896919076',
    projectId: 'geoerechim-af7e2',
    authDomain: 'geoerechim-af7e2.firebaseapp.com',
    storageBucket: 'geoerechim-af7e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqza7VIeD1tx-znVMYMmI5pyV1b9OtevQ',
    appId: '1:368896919076:android:a79cda4239846154043ab1',
    messagingSenderId: '368896919076',
    projectId: 'geoerechim-af7e2',
    storageBucket: 'geoerechim-af7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5HC4oj6LzrOZ8l1JQxH2WcKCtA_btEsc',
    appId: '1:368896919076:ios:7b51e748e8cabbec043ab1',
    messagingSenderId: '368896919076',
    projectId: 'geoerechim-af7e2',
    storageBucket: 'geoerechim-af7e2.firebasestorage.app',
    iosBundleId: 'com.example.geoerechim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5HC4oj6LzrOZ8l1JQxH2WcKCtA_btEsc',
    appId: '1:368896919076:ios:7b51e748e8cabbec043ab1',
    messagingSenderId: '368896919076',
    projectId: 'geoerechim-af7e2',
    storageBucket: 'geoerechim-af7e2.firebasestorage.app',
    iosBundleId: 'com.example.geoerechim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkEhvOKoOEtbloWWI2mRIZgTHnfM_TbsA',
    appId: '1:368896919076:web:463f9db556b95dd8043ab1',
    messagingSenderId: '368896919076',
    projectId: 'geoerechim-af7e2',
    authDomain: 'geoerechim-af7e2.firebaseapp.com',
    storageBucket: 'geoerechim-af7e2.firebasestorage.app',
  );
}
